import { FormEvent, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { EmptyState } from "../../components/EmptyState";
import { ErrorState } from "../../components/ErrorState";
import { LoadingState } from "../../components/LoadingState";
import { useItinerary } from "./useItinerary";
import type { ItineraryActivity, ItineraryDay } from "./types";

type Mode = "timeline" | "calendar";
const money = (value: number) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const displayDate = (value: string, includeYear = false) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric", ...(includeYear ? { year: "numeric" } : {}) });
const time = (activity: ItineraryActivity) => activity.startTime ? `${activity.startTime.slice(0, 5)}${activity.endTime ? ` – ${activity.endTime.slice(0, 5)}` : ""}` : "Any time";

export const ItineraryExperience = ({ mode }: { mode: Mode }) => {
  const { tripId } = useParams(); const state = useItinerary(tripId); const [collapsed, setCollapsed] = useState<Set<string>>(new Set()); const [editing, setEditing] = useState<ItineraryActivity | null>(null);
  if (state.isLoading && !state.itinerary) return <LoadingState label="Loading itinerary…" />;
  if (!state.itinerary) return <div className="space-y-3"><ErrorState message={state.error ?? "Unable to load itinerary."} /><button onClick={() => void state.load()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></div>;
  const { itinerary } = state;
  const toggle = (date: string) => setCollapsed((current) => { const next = new Set(current); next.has(date) ? next.delete(date) : next.add(date); return next; });
  return <div className="space-y-5"><section className="rounded-2xl bg-slate-900 px-5 py-6 text-white sm:px-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-200">{mode === "timeline" ? "Itinerary timeline" : "Trip calendar"}</p><h1 className="mt-1 text-3xl font-bold">{itinerary.trip.name}</h1><p className="mt-2 text-sm text-slate-300">{displayDate(itinerary.trip.startDate, true)} – {displayDate(itinerary.trip.endDate, true)} · {itinerary.summary.tripDays} days</p></div><ViewSwitch tripId={itinerary.trip.id} mode={mode} /></div><BudgetSummary tripTotal={itinerary.summary.tripTotal} budget={itinerary.summary.plannedBudget} remaining={itinerary.summary.remainingBudget} over={itinerary.summary.isOverBudget} /></section>
    {state.error && <ErrorState message={state.error} />}
    {itinerary.days.every((day) => day.activities.length === 0) && <EmptyState title="Your itinerary is clear" description="Add activities in the itinerary builder to see them arranged by day." />}
    {mode === "timeline" ? <Timeline days={itinerary.days} collapsed={collapsed} onToggle={toggle} saving={state.isSaving} onReorder={state.reorderDayActivities} onEdit={setEditing} /> : <Calendar days={itinerary.days} saving={state.isSaving} onEdit={setEditing} />}
    <p className="text-center text-sm text-slate-500">Trip total: <b className="text-slate-800">{money(itinerary.summary.tripTotal)}</b> · Activity estimates {money(itinerary.summary.estimatedActivityCost)} · Recorded expenses {money(itinerary.summary.totalSpent)}</p>
    {editing && <QuickEdit activity={editing} saving={state.isSaving} onCancel={() => setEditing(null)} onSave={(input) => { state.updateActivity(editing.id, input); setEditing(null); }} />}
  </div>;
};

const ViewSwitch = ({ tripId, mode }: { tripId: string; mode: Mode }) => <div className="inline-flex rounded-lg bg-white/10 p-1 text-sm"><Link to={`/trips/${tripId}/itinerary`} className={`rounded-md px-3 py-2 font-semibold ${mode === "timeline" ? "bg-white text-slate-900" : "text-slate-200 hover:text-white"}`}>Timeline</Link><Link to={`/trips/${tripId}/calendar`} className={`rounded-md px-3 py-2 font-semibold ${mode === "calendar" ? "bg-white text-slate-900" : "text-slate-200 hover:text-white"}`}>Calendar</Link></div>;
const BudgetSummary = ({ tripTotal, budget, remaining, over }: { tripTotal: number; budget: number | null; remaining: number | null; over: boolean }) => <div className={`mt-5 flex flex-wrap items-center gap-x-5 gap-y-2 rounded-xl px-4 py-3 text-sm ${over ? "bg-red-500/20 text-red-50" : "bg-white/10 text-slate-100"}`}><span><span className="text-slate-300">Committed</span> <b>{money(tripTotal)}</b></span>{budget === null ? <span className="text-slate-300">No budget set</span> : <><span><span className="text-slate-300">Budget</span> <b>{money(budget)}</b></span><span className="font-semibold">{over ? `${money(Math.abs(remaining ?? 0))} over budget` : `${money(remaining ?? 0)} remaining`}</span></>}</div>;

const Timeline = ({ days, collapsed, onToggle, saving, onReorder, onEdit }: { days: ItineraryDay[]; collapsed: Set<string>; onToggle: (date: string) => void; saving: boolean; onReorder: (day: ItineraryDay, source: string, target: string) => void; onEdit: (activity: ItineraryActivity) => void }) => {
  const [dragging, setDragging] = useState<string | null>(null); let previousCity: string | null = null;
  return <div className="space-y-4">{days.map((day) => { const transition = day.city?.name !== previousCity; previousCity = day.city?.name ?? null; const isExpanded = !collapsed.has(day.date); return <section key={day.date} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{transition && <div className="border-b border-sky-100 bg-sky-50 px-5 py-3 text-sm font-semibold text-sky-800">{day.city ? <>City stop {day.city.stopOrder}: {day.city.name}, {day.city.country}</> : "Travel day · city not assigned"}</div>}<button onClick={() => onToggle(day.date)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left"><div><p className="font-bold text-slate-900">{displayDate(day.date, true)}</p><p className="mt-1 text-sm text-slate-500">{day.activities.length} {day.activities.length === 1 ? "activity" : "activities"} · Daily total {money(day.dailyCost.totalCommitted)}</p></div><span className="text-sm font-semibold text-sky-700">{isExpanded ? "Collapse −" : "Expand +"}</span></button>{isExpanded && <div className="border-t border-slate-100 p-4"><div className="space-y-2">{day.activities.length ? day.activities.map((activity) => <ActivityCard key={activity.id} activity={activity} saving={saving} draggable onDragStart={() => setDragging(activity.id)} onDrop={() => { if (dragging) onReorder(day, dragging, activity.id); setDragging(null); }} onEdit={onEdit} />) : <p className="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">No activities planned for this day.</p>}</div></div>}</section>; })}</div>;
};
const Calendar = ({ days, saving, onEdit }: { days: ItineraryDay[]; saving: boolean; onEdit: (activity: ItineraryActivity) => void }) => <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid min-w-[700px] grid-cols-7 border-b border-slate-200 bg-slate-50">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((label) => <p key={label} className="px-3 py-3 text-center text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p>)}</div><div className="grid min-w-[700px] grid-cols-7">{Array.from({ length: new Date(`${days[0].date}T00:00:00`).getDay() }).map((_, index) => <div key={`empty-${index}`} className="min-h-40 border-b border-r border-slate-100 bg-slate-50/40" />)}{days.map((day) => <article key={day.date} className="min-h-40 border-b border-r border-slate-100 p-2"><div className="flex items-start justify-between"><p className="text-sm font-bold text-slate-800">{new Date(`${day.date}T00:00:00`).getDate()}</p><p className="text-[11px] font-semibold text-slate-500">{money(day.dailyCost.totalCommitted)}</p></div>{day.city && <p className="mt-1 truncate text-[11px] font-semibold text-sky-700">{day.city.name}</p>}<div className="mt-2 space-y-1">{day.activities.slice(0, 3).map((activity) => <button key={activity.id} disabled={saving} onClick={() => onEdit(activity)} className="block w-full truncate rounded bg-sky-50 px-1.5 py-1 text-left text-[11px] text-sky-900 hover:bg-sky-100"><b>{activity.startTime?.slice(0, 5) ?? "Any"}</b> {activity.name}</button>)}{day.activities.length > 3 && <p className="text-[11px] font-semibold text-slate-500">+{day.activities.length - 3} more</p>}</div></article>)}</div></div>;
const ActivityCard = ({ activity, saving, draggable, onDragStart, onDrop, onEdit }: { activity: ItineraryActivity; saving: boolean; draggable: boolean; onDragStart: () => void; onDrop: () => void; onEdit: (activity: ItineraryActivity) => void }) => <article draggable={draggable} onDragStart={onDragStart} onDragOver={(event) => event.preventDefault()} onDrop={onDrop} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 transition hover:border-sky-300"><span className="cursor-grab text-slate-400" aria-label="Drag to reorder">⠿</span><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-800">{activity.name}</p><p className="text-xs text-slate-500">{time(activity)} · {money(activity.cost)}{activity.durationMinutes ? ` · ${activity.durationMinutes} min` : ""}</p></div><button disabled={saving} onClick={() => onEdit(activity)} className="text-sm font-semibold text-sky-700 disabled:opacity-50">Edit</button></article>;
const QuickEdit = ({ activity, saving, onCancel, onSave }: { activity: ItineraryActivity; saving: boolean; onCancel: () => void; onSave: (input: Pick<ItineraryActivity, "startTime" | "endTime" | "cost">) => void }) => { const [startTime, setStartTime] = useState(activity.startTime ?? ""); const [endTime, setEndTime] = useState(activity.endTime ?? ""); const [cost, setCost] = useState(String(activity.cost)); const [error, setError] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (Boolean(startTime) !== Boolean(endTime)) return setError("Provide both start and end times."); if (startTime && endTime && endTime <= startTime) return setError("End time must be later than start time."); if (!cost || Number(cost) < 0) return setError("Cost must be zero or more."); onSave({ startTime: startTime || null, endTime: endTime || null, cost: Number(cost) }); }; return <div role="dialog" aria-modal="true" aria-labelledby="quick-edit-title" className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-4 sm:items-center sm:justify-center"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="quick-edit-title" className="text-xl font-bold text-slate-900">Edit {activity.name}</h2><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Start time<input type="time" value={startTime} onChange={(event) => setStartTime(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><label className="text-sm font-semibold">End time<input type="time" value={endTime} onChange={(event) => setEndTime(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label><label className="col-span-2 text-sm font-semibold">Cost (USD)<input type="number" min="0" step="1" value={cost} onChange={(event) => setCost(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-2 font-normal" /></label></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="px-3 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save changes"}</button></div></form></div>; };
