import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { apiClient } from "../api/client";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";
import { LoadingState } from "../components/LoadingState";

type Category = "transport" | "accommodation" | "activity" | "meal" | "other";
type Expense = { id: string; category: Category; description: string | null; amount: number; expenseDate: string };
type Daily = { date: string; total: number; percentageOfPlannedDailyBudget: number | null; isOverBudget: boolean; overBudgetAmount: number };
type BudgetSummary = { plannedBudget: number | null; totalSpent: number; remainingBudget: number | null; percentageUsed: number | null; transportTotal: number; accommodationTotal: number; activityTotal: number; mealTotal: number; otherTotal: number; averageDailyCost: number; estimatedActivityCost: number; totalEstimatedCost: number; projectedRemainingBudget: number | null; categoryPercentages: Record<Category, number>; dailyExpenseBreakdown: Daily[]; overBudgetDays: Daily[]; isOverBudget: boolean; overBudgetAmount: number };
const categories: { id: Category; label: string; color: string }[] = [{ id: "transport", label: "Transport", color: "bg-sky-500" }, { id: "accommodation", label: "Accommodation", color: "bg-violet-500" }, { id: "activity", label: "Activities", color: "bg-amber-500" }, { id: "meal", label: "Meals", color: "bg-rose-500" }, { id: "other", label: "Other", color: "bg-slate-500" }];
const money = (value: number | null) => value === null ? "No budget" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const displayDate = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });

export const BudgetPage = () => {
  const { tripId } = useParams(); const [summary, setSummary] = useState<BudgetSummary | null>(null); const [expenses, setExpenses] = useState<Expense[] | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [editing, setEditing] = useState<Expense | "new" | null>(null);
  const load = useCallback(async () => { if (!tripId) { setError("Trip not found."); return; } setError(null); try { const [budget, expenseData] = await Promise.all([apiClient<{ budgetSummary: BudgetSummary }>(`/trips/${tripId}/budget-summary`), apiClient<{ expenses: Expense[] }>(`/trips/${tripId}/expenses`)]); setSummary(budget.budgetSummary); setExpenses(expenseData.expenses); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load budget details."); } }, [tripId]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (action: () => Promise<unknown>) => { setSaving(true); setError(null); try { await action(); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save expense."); } finally { setSaving(false); } };
  if (!summary || !expenses) { if (error) return <div className="space-y-3"><ErrorState message={error} /><button onClick={() => void load()} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></div>; return <LoadingState label="Loading budget…" />; }
  const categoryValues = categories.map((item) => ({ ...item, amount: summary[`${item.id === "activity" ? "activity" : item.id}Total` as keyof BudgetSummary] as number, percentage: summary.categoryPercentages[item.id] }));
  return <div className="space-y-6"><section className={`rounded-2xl p-6 text-white ${summary.isOverBudget ? "bg-red-800" : "bg-slate-900"}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-200">Trip budget</p><h1 className="mt-1 text-3xl font-bold">Budget & cost breakdown</h1><p className="mt-2 text-sm text-slate-300">Actual expenses and scheduled activity estimates, from your trip data.</p></div><button onClick={() => setEditing("new")} className="rounded-lg bg-white px-4 py-2.5 text-sm font-bold text-slate-900 hover:bg-slate-100">+ Add expense</button></div><div className="mt-6 flex flex-wrap gap-x-7 gap-y-3 rounded-xl bg-white/10 p-4 text-sm"><span><span className="text-slate-300">Planned</span> <b>{money(summary.plannedBudget)}</b></span><span><span className="text-slate-300">Projected total</span> <b>{money(summary.totalEstimatedCost)}</b></span><span className="font-semibold">{summary.plannedBudget === null ? "Set a trip budget to track remaining funds" : summary.isOverBudget ? `${money(summary.overBudgetAmount)} over budget` : `${money(summary.projectedRemainingBudget)} remaining`}</span></div></section>
    {error && <ErrorState message={error} />}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Planned budget" value={money(summary.plannedBudget)} /><Metric label="Spent so far" value={money(summary.totalSpent)} /><Metric label="Projected trip total" value={money(summary.totalEstimatedCost)} /><Metric label="Remaining amount" value={summary.plannedBudget === null ? "No budget" : money(summary.projectedRemainingBudget)} /><Metric label="Average daily cost" value={money(summary.averageDailyCost)} /></section>
    {summary.isOverBudget && <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><b>Projected budget exceeded.</b> Your committed trip total is {money(summary.overBudgetAmount)} above the planned budget.</div>}
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-900">Category breakdown</h2><p className="mt-1 text-sm text-slate-500">Expense categories from recorded costs.</p><div className="mt-5 space-y-4">{categoryValues.map((category) => <div key={category.id}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold text-slate-700">{category.label}</span><span className="text-slate-500">{money(category.amount)} · {category.percentage}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${category.color}`} style={{ width: `${category.percentage}%` }} /></div></div>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-900">Daily expense breakdown</h2><p className="mt-1 text-sm text-slate-500">Compared with the backend-calculated daily budget allowance.</p>{summary.dailyExpenseBreakdown.length ? <div className="mt-5 space-y-3">{summary.dailyExpenseBreakdown.map((day) => <div key={day.date}><div className="flex justify-between gap-3 text-sm"><span className="font-medium text-slate-700">{displayDate(day.date)}</span><span className={day.isOverBudget ? "font-bold text-red-700" : "text-slate-500"}>{money(day.total)}{day.isOverBudget && " · over daily budget"}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${day.isOverBudget ? "bg-red-500" : "bg-sky-500"}`} style={{ width: `${Math.min(day.percentageOfPlannedDailyBudget ?? 0, 100)}%` }} /></div></div>)}</div> : <div className="mt-5"><EmptyState title="No recorded daily expenses" description="Add an expense to see its daily budget impact." /></div>}</section></div>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-slate-900">Expenses</h2><p className="mt-1 text-sm text-slate-500">Add, update, or remove recorded trip costs.</p></div><button onClick={() => setEditing("new")} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:border-sky-300 hover:text-sky-700">Add expense</button></div>{expenses.length ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Date</th><th className="pb-3">Category</th><th className="pb-3">Description</th><th className="pb-3 text-right">Amount</th><th className="pb-3" /></tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id} className="border-b border-slate-100"><td className="py-3 text-slate-600">{displayDate(expense.expenseDate)}</td><td className="py-3 capitalize text-slate-700">{expense.category}</td><td className="py-3 text-slate-600">{expense.description || "—"}</td><td className="py-3 text-right font-semibold text-slate-900">{money(expense.amount)}</td><td className="py-3 text-right"><button disabled={saving} onClick={() => setEditing(expense)} className="mr-3 font-semibold text-sky-700 disabled:opacity-50">Edit</button><button disabled={saving} onClick={() => { if (window.confirm("Delete this expense?")) void mutate(() => apiClient(`/trips/${tripId}/expenses/${expense.id}`, { method: "DELETE" })); }} className="font-semibold text-red-600 disabled:opacity-50">Delete</button></td></tr>)}</tbody></table></div> : <div className="mt-5"><EmptyState title="No expenses yet" description="Record transport, stays, meals, and other trip costs here." /></div>}</section>
    {summary.overBudgetDays.length > 0 && <section className="rounded-2xl border border-red-200 bg-red-50 p-5 sm:p-6"><h2 className="text-xl font-bold text-red-900">Over-budget days</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{summary.overBudgetDays.map((day) => <div key={day.date} className="rounded-xl bg-white p-3 text-sm"><p className="font-semibold text-slate-900">{displayDate(day.date)}</p><p className="mt-1 text-red-700">{money(day.total)} · {money(day.overBudgetAmount)} over</p></div>)}</div></section>}
    {editing && <ExpenseDialog expense={editing === "new" ? undefined : editing} saving={saving} onCancel={() => setEditing(null)} onSave={(input) => void mutate(() => editing === "new" ? apiClient(`/trips/${tripId}/expenses`, { method: "POST", body: JSON.stringify(input) }) : apiClient(`/trips/${tripId}/expenses/${editing.id}`, { method: "PUT", body: JSON.stringify(input) }))} />}
  </div>;
};

const Metric = ({ label, value }: { label: string; value: string }) => <article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>;
const ExpenseDialog = ({ expense, saving, onCancel, onSave }: { expense?: Expense; saving: boolean; onCancel: () => void; onSave: (input: Omit<Expense, "id">) => void }) => { const [error, setError] = useState(""); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const amount = Number(form.get("amount")); const expenseDate = String(form.get("expenseDate")); if (!expenseDate) return setError("Choose an expense date."); if (!Number.isFinite(amount) || amount < 0) return setError("Enter a valid non-negative amount."); onSave({ category: String(form.get("category")) as Category, description: String(form.get("description")).trim() || null, amount, expenseDate }); }; return <div role="dialog" aria-modal="true" aria-labelledby="expense-title" className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-4 sm:items-center sm:justify-center"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="expense-title" className="text-xl font-bold text-slate-900">{expense ? "Edit expense" : "Add expense"}</h2><div className="mt-5 grid gap-4"><label className="text-sm font-semibold text-slate-700">Category<select name="category" defaultValue={expense?.category ?? "transport"} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2.5 font-normal">{categories.map((category) => <option key={category.id} value={category.id}>{category.label}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Amount (USD)<input required name="amount" type="number" min="0" step="0.01" defaultValue={expense?.amount ?? ""} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Date<input required name="expenseDate" type="date" defaultValue={expense?.expenseDate ?? ""} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Description <span className="font-normal text-slate-400">(optional)</span><input name="description" defaultValue={expense?.description ?? ""} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="px-3 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save expense"}</button></div></form></div>; };
