import { FormEvent, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ApiError, apiClient } from "../api/client";

type TripResponse = { trip: { id: string } };
type FieldErrors = Partial<Record<"name" | "startDate" | "endDate" | "budget" | "coverImage", string>>;

export const CreateTripPage = () => {
  const navigate = useNavigate(); const [errors, setErrors] = useState<FieldErrors>({}); const [serverError, setServerError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get("name")).trim(); const startDate = String(form.get("startDate")); const endDate = String(form.get("endDate")); const description = String(form.get("description")).trim(); const budgetValue = String(form.get("budget")); const coverImage = String(form.get("coverImage")).trim(); const nextErrors: FieldErrors = {};
    if (!name) nextErrors.name = "Give your trip a name."; if (!startDate) nextErrors.startDate = "Choose a start date."; if (!endDate) nextErrors.endDate = "Choose an end date."; if (startDate && endDate && endDate < startDate) nextErrors.endDate = "The end date must be on or after the start date."; if (budgetValue && (Number.isNaN(Number(budgetValue)) || Number(budgetValue) < 0)) nextErrors.budget = "Budget cannot be negative.";
    if (coverImage) try { new URL(coverImage); } catch { nextErrors.coverImage = "Enter a valid image URL."; }
    setErrors(nextErrors); setServerError(null); if (Object.keys(nextErrors).length) return;
    setSubmitting(true); try { const { trip } = await apiClient<TripResponse>("/trips", { method: "POST", body: JSON.stringify({ name, startDate, endDate, description: description || undefined, budget: budgetValue ? Number(budgetValue) : null, coverImage: coverImage || undefined }) }); navigate(`/trips/${trip.id}`, { replace: true }); } catch (reason) { setServerError(reason instanceof ApiError ? reason.message : "Unable to create your trip. Please try again."); } finally { setSubmitting(false); }
  };
  const field = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-slate-900 outline-none transition focus:border-sky-600 focus:ring-2 focus:ring-sky-100";
  return <div className="mx-auto max-w-2xl"><div className="rounded-2xl bg-slate-900 px-6 py-7 text-white"><p className="text-sm font-semibold uppercase tracking-wider text-sky-200">New journey</p><h1 className="mt-2 font-serif text-3xl">Plan the essentials first.</h1><p className="mt-2 text-sm text-slate-300">You can add places and activities once your trip is created.</p></div><form noValidate onSubmit={submit} className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5"><label className="text-sm font-semibold text-slate-700">Trip name<input autoFocus required name="name" aria-invalid={Boolean(errors.name)} className={field} placeholder="e.g. Spring in Kyoto" />{errors.name && <span className="mt-1 block text-xs font-medium text-red-600">{errors.name}</span>}</label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Start date<input required type="date" name="startDate" aria-invalid={Boolean(errors.startDate)} className={field} />{errors.startDate && <span className="mt-1 block text-xs font-medium text-red-600">{errors.startDate}</span>}</label><label className="text-sm font-semibold text-slate-700">End date<input required type="date" name="endDate" aria-invalid={Boolean(errors.endDate)} className={field} />{errors.endDate && <span className="mt-1 block text-xs font-medium text-red-600">{errors.endDate}</span>}</label></div><label className="text-sm font-semibold text-slate-700">Description <span className="font-normal text-slate-400">(optional)</span><textarea name="description" rows={4} className={`${field} resize-y`} placeholder="A short note about the trip…" /></label><label className="text-sm font-semibold text-slate-700">Budget <span className="font-normal text-slate-400">(USD, optional)</span><input type="number" name="budget" min="0" step="1" inputMode="decimal" aria-invalid={Boolean(errors.budget)} className={field} placeholder="0" />{errors.budget && <span className="mt-1 block text-xs font-medium text-red-600">{errors.budget}</span>}</label><label className="text-sm font-semibold text-slate-700">Cover image URL <span className="font-normal text-slate-400">(optional)</span><input type="url" name="coverImage" aria-invalid={Boolean(errors.coverImage)} className={field} placeholder="https://…" />{errors.coverImage && <span className="mt-1 block text-xs font-medium text-red-600">{errors.coverImage}</span>}</label></div>{serverError && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{serverError}</p>}<div className="mt-7 flex justify-end"><button disabled={submitting} className="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-bold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60">{submitting ? "Creating trip…" : "Create trip"}</button></div></form></div>;
};
