import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiClient } from "../api/client";
import { ErrorState } from "../components/ErrorState";
import { EmptyState } from "../components/EmptyState";
import { useAuth } from "../hooks/useAuth";

type Trip = { id: string; name: string; startDate: string; endDate: string; budget: number | null; destinationCount: number; estimatedExpenseTotal: number };
type City = { id: string; name: string; country: string; description: string | null; image: string | null };
type Dashboard = { tripCount: number; budgetHighlights: { plannedBudget: number; estimatedExpenseTotal: number; actualExpenseTotal: number }; upcomingTrips: Trip[]; recentTrips: Trip[] };
const money = (value: number | null | undefined) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value ?? 0);
const dates = (trip: Trip) => `${new Date(`${trip.startDate}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric" })} – ${new Date(`${trip.endDate}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
const TripRow = ({ trip }: { trip: Trip }) => <Link to={`/trips/${trip.id}/itinerary`} className="group flex items-center justify-between gap-4 rounded-xl border border-slate-100 bg-white p-4 transition hover:border-sky-200 hover:shadow-sm"><div className="min-w-0"><p className="truncate font-semibold text-slate-800 group-hover:text-sky-700">{trip.name}</p><p className="mt-1 text-sm text-slate-500">{dates(trip)} · {trip.destinationCount} {trip.destinationCount === 1 ? "destination" : "destinations"}</p></div><span className="shrink-0 text-sm font-medium text-slate-700">{money(trip.budget)}</span></Link>;
const Skeleton = () => <div className="animate-pulse space-y-7"><div className="h-28 rounded-2xl bg-slate-200" /><div className="grid gap-4 md:grid-cols-3">{[1, 2, 3].map((x) => <div key={x} className="h-32 rounded-2xl bg-slate-200" />)}</div><div className="grid gap-6 lg:grid-cols-2"><div className="h-72 rounded-2xl bg-slate-200" /><div className="h-72 rounded-2xl bg-slate-200" /></div></div>;

export const DashboardPage = () => {
  const { user } = useAuth(); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [cities, setCities] = useState<City[]>([]); const [error, setError] = useState<string | null>(null);
  const load = () => { setError(null); Promise.all([apiClient<{ dashboard: Dashboard }>("/dashboard"), apiClient<{ cities: City[] }>("/cities?limit=4")]).then(([d, c]) => { setDashboard(d.dashboard); setCities(c.cities); }).catch((reason: Error) => setError(reason.message)); };
  useEffect(load, []);
  if (!dashboard && !error) return <Skeleton />;
  if (error) return <div className="space-y-4"><ErrorState message={error} /><button onClick={load} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></div>;
  const budget = dashboard!.budgetHighlights;
  return <div className="space-y-7"><section className="relative overflow-hidden rounded-2xl bg-slate-900 px-6 py-7 text-white sm:px-8"><div className="absolute -right-12 -top-16 h-48 w-48 rounded-full bg-sky-400/20" /><div className="relative flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-sky-200">Your travel desk</p><h1 className="mt-2 font-serif text-3xl tracking-tight sm:text-4xl">Welcome back, {user?.name?.split(" ")[0] ?? "traveler"}.</h1><p className="mt-2 text-sm text-slate-300">Keep your next escape moving and your travel budget in view.</p></div><Link to="/trips/new" className="inline-flex shrink-0 justify-center rounded-lg bg-sky-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-sky-300">+ Plan new trip</Link></div></section><section className="grid gap-4 md:grid-cols-3"><Stat label="Trips planned" value={String(dashboard!.tripCount)} note="Across your travel journal" /><Stat label="Total budget" value={money(budget.plannedBudget)} note={`${money(budget.estimatedExpenseTotal)} estimated activities`} /><Stat label="Recorded spend" value={money(budget.actualExpenseTotal)} note="Logged across all trips" /></section><section className="grid gap-6 lg:grid-cols-2"><TripSection title="Upcoming trips" trips={dashboard!.upcomingTrips} emptyTitle="Nothing on the horizon" emptyDescription="Start a new trip when inspiration strikes." /><TripSection title="Recent trips" trips={dashboard!.recentTrips} emptyTitle="Your trips will appear here" emptyDescription="Plan your first journey to start your collection." /></section><section><p className="text-sm font-semibold uppercase tracking-wider text-sky-700">Popular now</p><h2 className="mt-1 text-xl font-bold text-slate-900">Find your next city</h2>{cities.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cities.map((city) => <article key={city.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="h-28 bg-slate-100">{city.image && <img src={city.image} alt="" className="h-full w-full object-cover" />}</div><div className="p-4"><h3 className="font-bold text-slate-900">{city.name}</h3><p className="text-sm text-slate-500">{city.country}</p><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-500">{city.description}</p></div></article>)}</div> : <div className="mt-4"><EmptyState title="No destinations available" description="Recommendations will appear once city data is available." /></div>}</section></div>;
};
const Stat = ({ label, value, note }: { label: string; value: string; note: string }) => <article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{note}</p></article>;
const TripSection = ({ title, trips, emptyTitle, emptyDescription }: { title: string; trips: Trip[]; emptyTitle: string; emptyDescription: string }) => <div><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold text-slate-900">{title}</h2><Link to="/trips" className="text-sm font-semibold text-sky-700">View all</Link></div><div className="space-y-3">{trips.length ? trips.map((trip) => <TripRow key={trip.id} trip={trip} />) : <EmptyState title={emptyTitle} description={emptyDescription} />}</div></div>;
