import { FormEvent, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiClient } from "../api/client";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";

type Trip = { id: string; name: string; startDate: string; endDate: string; budget: number | null; destinationCount: number; coverImage: string | null };
const money = (value: number | null) => value === null ? "No budget set" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const dates = (trip: Trip) => `${new Date(`${trip.startDate}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })} – ${new Date(`${trip.endDate}T00:00:00`).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
const status = (trip: Trip) => { const today = new Date(); today.setHours(0, 0, 0, 0); const start = new Date(`${trip.startDate}T00:00:00`); const end = new Date(`${trip.endDate}T00:00:00`); return end < today ? "Completed" : start <= today ? "In progress" : "Upcoming"; };

export const MyTripsPage = () => {
  const [trips, setTrips] = useState<Trip[] | null>(null); const [error, setError] = useState<string | null>(null); const [busyId, setBusyId] = useState<string | null>(null); const [editing, setEditing] = useState<Trip | null>(null);
  const load = () => { setError(null); apiClient<{ trips: Trip[] }>("/trips").then(({ trips: data }) => setTrips(data)).catch((reason: Error) => setError(reason.message)); };
  useEffect(load, []);
  const remove = async (trip: Trip) => { if (!window.confirm(`Delete “${trip.name}”? This cannot be undone.`)) return; setBusyId(trip.id); try { await apiClient<void>(`/trips/${trip.id}`, { method: "DELETE" }); setTrips((current) => current?.filter(({ id }) => id !== trip.id) ?? null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete this trip."); } finally { setBusyId(null); } };
  const save = async (input: Pick<Trip, "name" | "startDate" | "endDate" | "budget">) => { if (!editing) return; setBusyId(editing.id); try { const { trip } = await apiClient<{ trip: Trip }>(`/trips/${editing.id}`, { method: "PUT", body: JSON.stringify(input) }); setTrips((current) => current?.map((item) => item.id === trip.id ? { ...item, ...trip } : item) ?? null); setEditing(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save this trip."); } finally { setBusyId(null); } };
  if (trips === null && !error) return <div className="grid gap-5 md:grid-cols-2">{[1, 2, 3, 4].map((x) => <div key={x} className="h-64 animate-pulse rounded-2xl bg-slate-200" />)}</div>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-700">Travel journal</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">My trips</h1><p className="mt-2 text-sm text-slate-500">Every journey, gathered in one place.</p></div><Link to="/trips/new" className="inline-flex justify-center rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white hover:bg-slate-800">+ Plan new trip</Link></div>{error && <div className="space-y-3"><ErrorState message={error} /><button onClick={load} className="text-sm font-semibold text-sky-700">Try again</button></div>}{trips?.length === 0 ? <EmptyState title="Your passport is waiting" description="Create a trip to begin organizing your next journey." /> : <div className="grid gap-5 md:grid-cols-2">{trips?.map((trip) => <TripCard key={trip.id} trip={trip} busy={busyId === trip.id} onEdit={() => setEditing(trip)} onDelete={() => remove(trip)} />)}</div>}{editing && <EditDialog trip={editing} saving={busyId === editing.id} onCancel={() => setEditing(null)} onSave={save} />}</div>;
};

const TripCard = ({ trip, busy, onEdit, onDelete }: { trip: Trip; busy: boolean; onEdit: () => void; onDelete: () => void }) => <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="h-24 bg-gradient-to-r from-slate-800 to-sky-800">{trip.coverImage && <img src={trip.coverImage} alt="" className="h-full w-full object-cover" />}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${status(trip) === "Upcoming" ? "bg-sky-50 text-sky-700" : status(trip) === "In progress" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{status(trip)}</span><h2 className="mt-3 text-xl font-bold text-slate-900">{trip.name}</h2></div><span className="text-right text-sm font-bold text-slate-700">{money(trip.budget)}</span></div><p className="mt-2 text-sm text-slate-500">{dates(trip)}</p><p className="mt-1 text-sm text-slate-500">{trip.destinationCount} {trip.destinationCount === 1 ? "destination" : "destinations"}</p><div className="mt-5 flex items-center gap-3 border-t border-slate-100 pt-4"><Link to={`/trips/${trip.id}`} className="text-sm font-semibold text-sky-700 hover:text-sky-800">View</Link><button onClick={onEdit} className="text-sm font-semibold text-slate-600 hover:text-slate-900">Edit</button><button disabled={busy} onClick={onDelete} className="ml-auto text-sm font-semibold text-red-600 hover:text-red-700 disabled:opacity-50">{busy ? "Deleting…" : "Delete"}</button></div></div></article>;

const EditDialog = ({ trip, saving, onCancel, onSave }: { trip: Trip; saving: boolean; onCancel: () => void; onSave: (input: Pick<Trip, "name" | "startDate" | "endDate" | "budget">) => Promise<void> }) => {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ name: String(form.get("name")), startDate: String(form.get("startDate")), endDate: String(form.get("endDate")), budget: form.get("budget") === "" ? null : Number(form.get("budget")) }); };
  return <div role="dialog" aria-modal="true" aria-labelledby="edit-trip-title" className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-4 sm:items-center sm:justify-center"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="edit-trip-title" className="text-xl font-bold text-slate-900">Edit trip</h2><div className="mt-5 grid gap-4"><label className="text-sm font-semibold text-slate-700">Trip name<input required name="name" defaultValue={trip.name} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold text-slate-700">Start<input required type="date" name="startDate" defaultValue={trip.startDate} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label><label className="text-sm font-semibold text-slate-700">End<input required type="date" name="endDate" defaultValue={trip.endDate} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label></div><label className="text-sm font-semibold text-slate-700">Budget (USD)<input type="number" min="0" step="1" name="budget" defaultValue={trip.budget ?? ""} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 font-normal" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save changes"}</button></div></form></div>;
};
