import { FormEvent, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ApiError, apiClient } from "../api/client";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";
import { LoadingState } from "../components/LoadingState";
import { useAuth } from "../hooks/useAuth";

type City = { id: string; name: string; country: string; region: string | null; image: string | null };
type SavedCity = City & { savedDestinationId: string; savedAt: string };
const languages = [{ value: "en", label: "English" }, { value: "es", label: "Spanish" }, { value: "fr", label: "French" }, { value: "de", label: "German" }, { value: "ja", label: "Japanese" }];

export const ProfilePage = () => {
  const { user, updateUser, logout } = useAuth(); const navigate = useNavigate(); const [name, setName] = useState(user?.name ?? ""); const [email, setEmail] = useState(user?.email ?? ""); const [profileImage, setProfileImage] = useState(user?.profileImage ?? ""); const [language, setLanguage] = useState(user?.language ?? "en"); const [saved, setSaved] = useState<SavedCity[] | null>(null); const [results, setResults] = useState<City[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState(false); const [confirmingDelete, setConfirmingDelete] = useState(false);
  useEffect(() => { if (user) { setName(user.name); setEmail(user.email); setProfileImage(user.profileImage ?? ""); setLanguage(user.language); } }, [user]);
  const loadSaved = async () => { try { setSaved((await apiClient<{ destinations: SavedCity[] }>("/saved-destinations")).destinations); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load saved destinations."); } };
  useEffect(() => { void loadSaved(); }, []);
  const saveProfile = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const nextName = name.trim(); const nextEmail = email.trim(); if (!nextName) return setError("Name is required."); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(nextEmail)) return setError("Enter a valid email address."); if (profileImage) try { new URL(profileImage); } catch { return setError("Enter a valid profile image URL."); } setSaving(true); setError(null); try { await updateUser({ name: nextName, email: nextEmail, profileImage: profileImage || null, language }); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Unable to save profile changes."); } finally { setSaving(false); } };
  const searchCities = async (event: FormEvent) => { event.preventDefault(); if (!query.trim()) return setResults([]); setError(null); try { setResults((await apiClient<{ cities: City[] }>(`/cities?search=${encodeURIComponent(query)}&limit=8`)).cities); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to search cities."); } };
  const saveCity = async (cityId: string) => { setSaving(true); setError(null); try { const response = await apiClient<{ destinations: SavedCity[] }>(`/saved-destinations/${cityId}`, { method: "POST" }); setSaved(response.destinations); setResults([]); setQuery(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save destination."); } finally { setSaving(false); } };
  const removeCity = async (cityId: string) => { setSaving(true); setError(null); try { await apiClient(`/saved-destinations/${cityId}`, { method: "DELETE" }); setSaved((current) => current?.filter((city) => city.id !== cityId) ?? null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to remove destination."); } finally { setSaving(false); } };
  const deleteAccount = async () => { setDeleting(true); setError(null); try { await apiClient<void>("/auth/me", { method: "DELETE" }); logout(); navigate("/signup", { replace: true }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete account."); setDeleting(false); } };
  if (!user) return <LoadingState label="Loading profile…" />;
  return <div className="mx-auto max-w-4xl space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-700">Account</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Profile & settings</h1><p className="mt-2 text-sm text-slate-500">Manage your account and save places for future travels.</p></div>{error && <ErrorState message={error} />}<section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-4"><div className="h-16 w-16 overflow-hidden rounded-full bg-sky-100">{user.profileImage ? <img src={user.profileImage} alt="Profile" className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center text-xl font-bold text-sky-700">{user.name.charAt(0).toUpperCase()}</span>}</div><div><h2 className="text-xl font-bold text-slate-900">Personal details</h2><p className="text-sm text-slate-500">Only you can view and change these details.</p></div></div><form onSubmit={saveProfile} noValidate className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Profile image URL <span className="font-normal text-slate-400">(optional)</span><input type="url" value={profileImage} onChange={(event) => setProfileImage(event.target.value)} placeholder="https://…" className="mt-1 w-full rounded-lg border border-slate-300 p-2.5 font-normal" /></label><label className="text-sm font-semibold text-slate-700">Language<select value={language} onChange={(event) => setLanguage(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2.5 font-normal">{languages.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><div className="flex items-end"><button disabled={saving} className="w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50 sm:w-auto">{saving ? "Saving…" : "Save changes"}</button></div></form></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-900">Saved destinations</h2><p className="mt-1 text-sm text-slate-500">Keep a personal shortlist of cities to explore.</p><form onSubmit={searchCities} className="mt-5 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cities" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /><button disabled={saving} className="rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white disabled:opacity-50">Search</button></form>{results.length > 0 && <div className="mt-3 divide-y divide-slate-100 rounded-xl border border-slate-200">{results.map((city) => <div key={city.id} className="flex items-center justify-between gap-3 p-3"><div><p className="font-semibold text-slate-800">{city.name}</p><p className="text-sm text-slate-500">{city.country}{city.region ? ` · ${city.region}` : ""}</p></div><button type="button" disabled={saving || Boolean(saved?.some((item) => item.id === city.id))} onClick={() => void saveCity(city.id)} className="rounded-lg border border-sky-200 px-3 py-1.5 text-sm font-semibold text-sky-700 disabled:opacity-50">{saved?.some((item) => item.id === city.id) ? "Saved" : "Save"}</button></div>)}</div>}{saved === null ? <LoadingState label="Loading saved cities…" /> : saved.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{saved.map((city) => <article key={city.id} className="flex overflow-hidden rounded-xl border border-slate-200"><div className="h-20 w-20 shrink-0 bg-slate-100">{city.image && <img src={city.image} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1 p-3"><p className="truncate font-semibold text-slate-800">{city.name}</p><p className="truncate text-sm text-slate-500">{city.country}</p><button disabled={saving} onClick={() => void removeCity(city.id)} className="mt-2 text-sm font-semibold text-red-600 disabled:opacity-50">Remove</button></div></article>)}</div> : <div className="mt-5"><EmptyState title="No saved destinations" description="Search for a city above and save it here for later." /></div>}</section>
    <section className="rounded-2xl border border-red-200 bg-red-50 p-5 sm:p-6"><h2 className="text-xl font-bold text-red-900">Delete account</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-red-800">This permanently removes your account and its trips. This action cannot be undone.</p><button onClick={() => setConfirmingDelete(true)} className="mt-4 rounded-lg border border-red-300 bg-white px-4 py-2.5 text-sm font-bold text-red-700 hover:bg-red-100">Delete account</button></section>
    {confirmingDelete && <DeleteDialog name={user.name} deleting={deleting} onCancel={() => setConfirmingDelete(false)} onConfirm={() => void deleteAccount()} />}</div>;
};

const DeleteDialog = ({ name, deleting, onCancel, onConfirm }: { name: string; deleting: boolean; onCancel: () => void; onConfirm: () => void }) => { const [confirmation, setConfirmation] = useState(""); return <div role="dialog" aria-modal="true" aria-labelledby="delete-account-title" className="fixed inset-0 z-50 flex items-end bg-slate-950/40 p-4 sm:items-center sm:justify-center"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="delete-account-title" className="text-xl font-bold text-slate-900">Delete your account?</h2><p className="mt-3 text-sm leading-6 text-slate-600">This permanently deletes {name}'s account, saved destinations, and all trips. Type <b>DELETE</b> to confirm.</p><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} aria-label="Type DELETE to confirm" className="mt-4 w-full rounded-lg border border-slate-300 p-2.5" /><div className="mt-6 flex justify-end gap-3"><button disabled={deleting} onClick={onCancel} className="px-3 py-2 text-sm font-semibold text-slate-600">Cancel</button><button disabled={deleting || confirmation !== "DELETE"} onClick={onConfirm} className="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{deleting ? "Deleting…" : "Delete account"}</button></div></div></div>; };
