import { useCallback, useEffect, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { ApiError, apiClient } from "../api/client";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";
import { LoadingState } from "../components/LoadingState";
import { useAuth } from "../hooks/useAuth";

type SharedActivity = { name: string; category: string; startTime: string | null; endTime: string | null; durationMinutes: number | null; cost: number; notes: string | null };
type SharedDay = { date: string; city: { name: string; country: string; image: string | null } | null; activities: SharedActivity[]; dailyCost: { actualExpenses: number; estimatedActivities: number; totalCommitted: number } };
type SharedItinerary = { trip: { id: string; name: string; description: string | null; startDate: string; endDate: string; plannedBudget: number | null }; days: SharedDay[]; summary: { totalSpent: number; estimatedActivityCost: number; tripTotal: number; plannedBudget: number | null; isOverBudget: boolean; overBudgetAmount: number } };
const money = (value: number | null) => value === null ? "No budget set" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const date = (value: string, year = false) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric", ...(year ? { year: "numeric" } : {}) });

export const SharedTripPage = () => {
  const { shareToken } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { isAuthenticated, isLoading: authLoading } = useAuth(); const [itinerary, setItinerary] = useState<SharedItinerary | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [copying, setCopying] = useState(false);
  const load = useCallback(async () => { if (!shareToken) { setError("This shared trip link is invalid."); setLoading(false); return; } setLoading(true); setError(null); try { setItinerary((await apiClient<{ itinerary: SharedItinerary }>(`/shared/${shareToken}`)).itinerary); } catch (reason) { setError(reason instanceof ApiError && reason.status === 404 ? "This shared trip is no longer available." : "Unable to load this shared trip. Please try again."); } finally { setLoading(false); } }, [shareToken]);
  useEffect(() => { void load(); }, [load]);
  const copyTrip = async () => { if (!shareToken) return; if (!isAuthenticated) { navigate("/login", { state: { from: location } }); return; } setCopying(true); setError(null); try { const { trip } = await apiClient<{ trip: { id: string } }>(`/shared/${shareToken}/copy`, { method: "POST" }); navigate(`/trips/${trip.id}`, { replace: true }); } catch (reason) { setError(reason instanceof ApiError && reason.status === 404 ? "This shared trip is no longer available." : "Unable to copy this trip. Please try again."); } finally { setCopying(false); } };
  if (loading) return <LoadingState label="Loading shared trip…" />;
  if (!itinerary) return <main className="mx-auto max-w-3xl px-4 py-12"><ErrorState message={error ?? "This shared trip is unavailable."} /><button onClick={() => void load()} className="mt-4 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></main>;
  const cities = itinerary.days.reduce<string[]>((result, day) => day.city && !result.includes(`${day.city.name}, ${day.city.country}`) ? [...result, `${day.city.name}, ${day.city.country}`] : result, []);
  let previousCity: string | null = null;
  return <main className="min-h-screen bg-slate-50 pb-12"><section className="bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14"><p className="text-sm font-semibold uppercase tracking-wider text-sky-300">Shared itinerary</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">{itinerary.trip.name}</h1><p className="mt-4 text-base text-slate-300">{date(itinerary.trip.startDate, true)} – {date(itinerary.trip.endDate, true)}</p></div><button disabled={authLoading || copying} onClick={() => void copyTrip()} className="rounded-lg bg-white px-5 py-3 text-sm font-bold text-slate-900 hover:bg-sky-50 disabled:cursor-not-allowed disabled:opacity-60">{authLoading ? "Checking account…" : copying ? "Copying trip…" : "Copy Trip"}</button></div>{itinerary.trip.description && <p className="mt-6 max-w-3xl text-base leading-7 text-slate-200">{itinerary.trip.description}</p>}<p className="mt-6 text-sm text-slate-400">This is a read-only public share. Copy it to personalize it in your own account.</p></div></section>
    <div className="mx-auto grid max-w-5xl gap-6 px-4 py-7 sm:px-6 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-5">{error && <ErrorState message={error} />}<section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-900">Itinerary</h2><div className="mt-5 space-y-4">{itinerary.days.map((day) => { const cityLabel = day.city ? `${day.city.name}, ${day.city.country}` : null; const transition = cityLabel !== previousCity; previousCity = cityLabel; return <article key={day.date} className="overflow-hidden rounded-xl border border-slate-200">{transition && <div className="bg-sky-50 px-4 py-2 text-sm font-semibold text-sky-800">{day.city ? `Arrive in ${cityLabel}` : "Travel day"}</div>}<div className="p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><h3 className="font-bold text-slate-900">{date(day.date, true)}</h3>{day.city && <p className="text-sm text-slate-500">{day.city.name}, {day.city.country}</p>}</div><p className="text-sm font-semibold text-slate-700">Daily total {money(day.dailyCost.totalCommitted)}</p></div>{day.activities.length ? <div className="mt-4 space-y-2">{day.activities.map((activity, index) => <div key={`${day.date}-${activity.name}-${index}`} className="flex items-start gap-3 rounded-lg bg-slate-50 p-3"><span className="mt-0.5 rounded bg-sky-100 px-2 py-1 text-xs font-bold text-sky-800">{activity.startTime?.slice(0, 5) ?? "Any"}</span><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{activity.name}</p><p className="text-xs text-slate-500">{activity.category}{activity.endTime ? ` · until ${activity.endTime.slice(0, 5)}` : ""}{activity.durationMinutes ? ` · ${activity.durationMinutes} min` : ""}</p>{activity.notes && <p className="mt-1 text-sm text-slate-600">{activity.notes}</p>}</div><span className="text-sm font-semibold text-slate-700">{money(activity.cost)}</span></div>)}</div> : <p className="mt-4 text-sm text-slate-500">No activities planned for this day.</p>}</div></article>; })}</div></section></div>
      <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold text-slate-900">Trip at a glance</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-slate-500">Cities</dt><dd className="mt-1 font-semibold text-slate-800">{cities.length ? cities.join(" · ") : "Not added yet"}</dd></div><div><dt className="text-slate-500">Budget</dt><dd className="mt-1 font-semibold text-slate-800">{money(itinerary.summary.plannedBudget)}</dd></div><div><dt className="text-slate-500">Trip total</dt><dd className="mt-1 font-semibold text-slate-800">{money(itinerary.summary.tripTotal)}</dd></div></dl>{itinerary.summary.plannedBudget !== null && <p className={`mt-4 rounded-lg p-3 text-sm font-semibold ${itinerary.summary.isOverBudget ? "bg-red-50 text-red-800" : "bg-emerald-50 text-emerald-800"}`}>{itinerary.summary.isOverBudget ? `${money(itinerary.summary.overBudgetAmount)} over budget` : "Within planned budget"}</p>}</section><section className="rounded-2xl border border-sky-100 bg-sky-50 p-5"><h2 className="font-bold text-slate-900">Make it your own</h2><p className="mt-2 text-sm leading-6 text-slate-600">Copy this itinerary to adapt dates, activities, and costs for your trip.</p><button disabled={authLoading || copying} onClick={() => void copyTrip()} className="mt-4 w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">{copying ? "Copying trip…" : "Copy Trip"}</button></section></aside></div>
    {itinerary.days.length === 0 && <div className="mx-auto max-w-5xl px-4"><EmptyState title="No itinerary days" description="This shared trip does not include any dates yet." /></div>}</main>;
};
