import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { apiClient } from "../api/client";
import { EmptyState } from "../components/EmptyState";
import { ErrorState } from "../components/ErrorState";

type Stop = { id: string; city: { name: string; country: string; image: string | null }; arrivalDate: string; departureDate: string };
type Trip = { id: string; name: string; description: string | null; startDate: string; endDate: string; budget: number | null; coverImage: string | null; stops: Stop[]; estimatedExpenseTotal: number };
type ScheduledActivity = { id: string };
const money = (amount: number | null) => new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(amount ?? 0);
const dateRange = (trip: Trip) => `${new Date(`${trip.startDate}T00:00:00`).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })} – ${new Date(`${trip.endDate}T00:00:00`).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" })}`;

export const TripDetailsPage = () => {
  const { tripId } = useParams(); const [trip, setTrip] = useState<Trip | null>(null); const [activityCount, setActivityCount] = useState<number>(0); const [error, setError] = useState<string | null>(null);
  const load = () => { if (!tripId) return; setError(null); Promise.all([apiClient<{ trip: Trip }>(`/trips/${tripId}?includeStops=true`), apiClient<{ scheduledActivities: ScheduledActivity[] }>(`/trips/${tripId}/activities`)]).then(([tripResponse, activityResponse]) => { setTrip(tripResponse.trip); setActivityCount(activityResponse.scheduledActivities.length); }).catch((reason: Error) => setError(reason.message)); };
  useEffect(load, [tripId]);
  if (!trip && !error) return <div className="animate-pulse space-y-5"><div className="h-52 rounded-2xl bg-slate-200" /><div className="grid gap-4 sm:grid-cols-3">{[1, 2, 3].map((x) => <div key={x} className="h-28 rounded-2xl bg-slate-200" />)}</div></div>;
  if (error) return <div className="space-y-4"><ErrorState message={error} /><button onClick={load} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Try again</button></div>;
  const currentTrip = trip!;
  return <div className="space-y-6"><section className="overflow-hidden rounded-2xl bg-slate-900 text-white"><div className="relative min-h-56 p-6 sm:p-8">{currentTrip.coverImage && <img src={currentTrip.coverImage} alt="" className="absolute inset-0 h-full w-full object-cover opacity-35" />}<div className="absolute inset-0 bg-slate-950/40" /><div className="relative"><Link to="/trips" className="text-sm font-semibold text-sky-200 hover:text-white">← All trips</Link><h1 className="mt-8 max-w-2xl font-serif text-4xl leading-tight">{currentTrip.name}</h1><p className="mt-3 text-sm text-slate-200">{dateRange(currentTrip)}</p>{currentTrip.description && <p className="mt-4 max-w-xl text-sm leading-6 text-slate-100">{currentTrip.description}</p>}</div></div></section><section className="grid gap-4 sm:grid-cols-3"><Metric label="Trip budget" value={currentTrip.budget === null ? "Not set" : money(currentTrip.budget)} /><Metric label="Estimated cost" value={money(currentTrip.estimatedExpenseTotal)} /><Metric label="Activities" value={String(activityCount)} /></section><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold uppercase tracking-wider text-sky-700">Route</p><h2 className="mt-1 text-xl font-bold text-slate-900">Cities on this trip</h2></div><Link to={`/trips/${currentTrip.id}/builder`} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:border-sky-300 hover:text-sky-700">Open itinerary</Link></div>{currentTrip.stops.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{currentTrip.stops.map((stop) => <div key={stop.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="h-12 w-12 overflow-hidden rounded-lg bg-slate-200">{stop.city.image && <img src={stop.city.image} alt="" className="h-full w-full object-cover" />}</div><div><p className="font-semibold text-slate-800">{stop.city.name}</p><p className="text-sm text-slate-500">{stop.city.country}</p></div></div>)}</div> : <div className="mt-5"><EmptyState title="Your route is open" description="Add cities to begin shaping this trip." /></div>}</section><section className="flex flex-col items-start justify-between gap-4 rounded-2xl border border-sky-100 bg-sky-50 p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold text-slate-900">Ready to shape the itinerary?</h2><p className="mt-1 text-sm text-slate-600">Add destinations and choose activities when you are ready.</p></div><Link to={`/trips/${currentTrip.id}/builder`} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Open itinerary</Link></section></div>;
};
const Metric = ({ label, value }: { label: string; value: string }) => <article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></article>;
